### PR TITLE
[25] Setup CI/CD

### LINKED ISSUE #25: [Chore] Setup CI/CD
## Why

The project should go alone with CI/CD to minimize aside chore works

## Who Benefits?

Developers and maintainers

### PR DESCRIPTION
**Pull request by nvminhtue**
close https://github.com/nvminhtue/elixir_internal_certificate/issues/25

## What happened

Set up CI/CD for Elixir Internal Certificate project
 
## Insight

- Config a staging app and a production app deployed on the Heroku site.
- The CD will be triggered when a new pull request is merged to develop(staging) or main(production).
 
## Proof Of Work
- CI and CD are run on Github Action by trigger on pull_request event. I hope everything goes well on workflow_run
image

- Production site: https://elixir-internal-certificate.herokuapp.com
- Staging site: https://stg-elixir-int-cert.herokuapp.com

### CODE REVIEW

**Comment by andyduong1920** [comment]
@nvminhtue did you test that workflow, or you will wait until we merged this PR into develop branch?

**Comment by nvminhtue** [comment]
> @nvminhtue did you test that workflow, or you will wait until we merged this PR into develop branch?

@andyduong1920 I just test for the pull_request trigger, not workflow_run. I just don't know to simulate merging action for triggering testing workflow

**Review by andyduong1920 — APPROVED** [review]

**Comment by junan** [comment]
@nvminhtue The PR title should match the issue title.

Also please add some description to the issue task also assign it to yourself
Screen Shot 2565-06-08 at 10 16 49 AM

**Review by junan — APPROVED** [review]

**Comment by nvminhtue** [comment]
> @nvminhtue The PR title should match the issue title.
> 
> Also please add some description to the issue task also assign it to yourself Screen Shot 2565-06-08 at 10 16 49 AM

@junan all set, take a look at it sometimes, thank you for reminding me.

**Pull request merged**
